---
name: Params-CallbackRequest
version: 1.19
author:
  - 'David Wheeler <david@kineticode.com>'
abstract: Functional and object-oriented callback architecture
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  Attribute::Handlers: 0.77
  Class::ISA: 0
  Exception::Class: 1.10
  Params::Validate: 0.59
  Test::Simple: 0.17
  perl: 5.006
build_requires:
  Module::Build: 0.2701
  Test::More: 0.17
recommends:
  Test::Pod: 1.20
provides:
  Params::Callback:
    file: lib/Params/Callback.pm
    version: 1.19
  Params::CallbackRequest:
    file: lib/Params/CallbackRequest.pm
    version: 1.19
  Params::CallbackRequest::Exceptions:
    file: lib/Params/CallbackRequest/Exceptions.pm
    version: 1.19
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
