---
name: Params-CallbackRequest
version: 1.15
author:
  - 'David Wheeler <david@kineticode.com>'
abstract: Functional and object-oriented callback architecture
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exception::Class: 1.10
  Params::Validate: 0.59
  Test::Simple: 0.17
build_requires:
  Test::Simple: 0.17
recommends:
  Attribute::Handlers: 0.77
  Class::ISA: 0
  perl: 5.6.0
provides:
  Params::Callback:
    file: lib/Params/Callback.pm
    version: 1.15
  Params::CallbackRequest:
    file: lib/Params/CallbackRequest.pm
    version: 1.15
  Params::CallbackRequest::Exceptions:
    file: lib/Params/CallbackRequest/Exceptions.pm
    version: 1.15
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
